//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityConsultationsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordID { get; set; }
        public int ConsultationID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string Status { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual Student Student { get; set; }
    }
}
